# Generated by Django 5.1.2 on 2025-12-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_chatmessage_id_alter_chatsession_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='interview_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='interview_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='recruiter_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='rejection_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('NEW', 'New / Pending'), ('AUTO_REJECTED', 'Auto Rejected'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('INTERVIEW_PASSED', 'Interview Passed'), ('INTERVIEW_REJECTED', 'Rejected after Interview'), ('HIRED', 'Hired')], default='NEW', max_length=30),
        ),
    ]
