# Generated by Django 5.1.2 on 2025-12-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_resume_interview_date_resume_interview_email_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('NEW', 'New / Pending'), ('SHORTLISTED', 'Shortlisted'), ('AUTO_REJECTED', 'Auto Rejected'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('INTERVIEW_PASSED', 'Interview Passed'), ('INTERVIEW_REJECTED', 'Rejected after Interview'), ('HIRED', 'Hired')], default='NEW', max_length=30),
        ),
    ]
