# Generated by Django 5.1.2 on 2025-12-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_resume_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='human_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='human_score_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
