# Generated by Django 5.1.2 on 2025-12-17 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_resume_human_score_resume_human_score_breakdown'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('INGESTED', 'Resume Ingested'), ('SCORED', 'AI Scored'), ('RESCORED', 'Rescored'), ('STATUS_CHANGE', 'Status Changed'), ('EMAIL_SENT', 'Email Sent'), ('NOTE_ADDED', 'Note Added'), ('FAVORITE', 'Marked as Favorite'), ('UNFAVORITE', 'Unmarked Favorite'), ('RATED', 'Manager Rated')], max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='jobs.resume')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
