# Generated by Django 5.1.2 on 2025-12-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_resumeactivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('NEW', 'New / Pending'), ('SHORTLISTED', 'Shortlisted'), ('AUTO_REJECTED', 'Auto Rejected'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('INTERVIEW_PASSED', 'Interview Passed'), ('INTERVIEW_REJECTED', 'Rejected after Interview'), ('REJECTED', 'Rejected'), ('HIRED', 'Hired')], default='NEW', max_length=30),
        ),
    ]
