# Generated by Django 6.0 on 2025-12-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_resume_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='candidate_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='candidate_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='candidate_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='linkedin_profile',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('NEW', 'New / Pending'), ('AUTO_REJECTED', 'Auto Rejected'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('INTERVIEW_PASSED', 'Interview Passed'), ('INTERVIEW_REJECTED', 'Rejected after Interview'), ('HIRED', 'Hired')], default='NEW', max_length=30),
        ),
    ]
