# Generated by Django 5.1.2 on 2026-01-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_resume_candidate_company_resume_candidate_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ingest_failures',
            field=models.IntegerField(default=0),
        ),
    ]
